name: nltocode-cpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.7.4
  - astor==0.7.1
  - matplotlib==3.3.4
  - networkx==2.5
  - pandas==1.1.1
  - pip
  - pytorch==1.6.0
  - pytorch-lightning==1.3.8
  - sentencepiece==0.1.95
  - cpuonly # replace with 'cudatoolkit=CUDA_VERSION' for GPU support
  - babel==2.9.0
  - records==0.5.3
  #- pip:
      #- babel==2.9.0
      #- records==0.5.3