name: nltocode-cuda111
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.7.0,<3.8.0
  - astor==0.8.1
  - matplotlib>=3.3.0,<4.0.0
  - networkx==2.5
  - pandas>=1.1.0,<1.2.0
  - pip
  - pytorch==1.9.0
  - pytorch-lightning=1.3.8
  - sentencepiece==0.1.95
  - cudatoolkit=11.1.1
  - babel==2.9.0
  - records==0.5.3
  - pip:
      - git+https://github.com/conala-corpus/conala-baseline.git@7d3e5821677cb02613a7cc43fb346745e3fa0731