name: scads-cai-prototype-gpu2
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python>=3.7.0,<3.8.0
  - astor==0.8.1
  - cudatoolkit==10.1.243
  - networkx==2.4
  - pandas==1.1.1
  - pip
  - pytorch==1.5.1
  - pytorch-lightning=1.2.4
  - sentencepiece==0.1.95
  - pip:
    - babel==2.9.0
    - records==0.5.3
