name: scads_jupyter_nli
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cookiecutter>=1.7.2,<1.8.0
  - jupyterlab>=3.0.6,<3.1.0
  - jupyter-packaging>=0.7.11,<0.8.0
  - nodejs>=15.3.0,<16.0.0

