name: scads_jupyter_nli
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=2.0.2
  - argon2-cffi=20.1.0
  - arrow=0.17.0
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - binaryornot=0.4.4
  - bleach=3.3.0
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=4.0.0
  - click=7.1.2
  - cookiecutter=1.7.2
  - cryptography=3.3.1
  - curl=7.71.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.10
  - gettext=0.19.8.1
  - git=2.30.0
  - icu=68.1
  - idna=2.10
  - importlib-metadata=3.4.0
  - importlib_metadata=3.4.0
  - ipykernel=5.1.0
  - ipython=7.20.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=2.11.3
  - jinja2-time=0.2.0
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-packaging=0.7.11
  - jupyter_client=6.1.11
  - jupyter_core=4.7.1
  - jupyter_server=1.2.2
  - jupyterlab=3.0.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.1.3
  - krb5=1.17.2
  - ld_impl_linux-64=2.35.1
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libnghttp2=1.41.0
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libuv=1.40.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbclassic=0.2.6
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - nodejs=15.3.0
  - notebook=6.2.0
  - openssl=1.1.1i
  - packaging=20.8
  - pandoc=2.11.4
  - pandocfilters=1.4.2
  - parso=0.8.1
  - pcre=8.44
  - perl=5.32.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.0.1
  - poyo=0.5.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.14
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.7.4
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.1
  - python-dateutil=2.8.1
  - python-slugify=4.0.1
  - python_abi=3.9
  - pytz=2021.1
  - pyzmq=22.0.1
  - readline=8.0
  - requests=2.25.1
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - sniffio=1.2.0
  - sqlite=3.34.0
  - terminado=0.9.2
  - testpath=0.4.4
  - text-unidecode=1.3
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - tzdata=2021a
  - unidecode=1.1.2
  - urllib3=1.26.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - whichcraft=0.6.1
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
